[theme]
base = "light"
primaryColor = "#00838f"
backgroundColor = "#edf1f5"
secondaryBackgroundColor = "#ffffff"
textColor = "#1a1a2e"
font = "sans serif"

[server]
port = 8501
headless = true
enableCORS = false
enableXsrfProtection = false
address = "0.0.0.0"
maxUploadSize = 200

[browser]
gatherUsageStats = false
serverAddress = "localhost"

[client]
toolbarMode = "minimal"
showErrorDetails = true
